Repository Sweepic/sweepic-Aos, pull requests merged in 2025-02, with the labels that each got.

#29 [SWEP-81] 사진 정리 앨범에 저장 구현
  app/src/main/java/com/umc/sweepic/domain/model/sweep/AlbumList.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/AlbumViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/SweepActivity.kt
Labels: FEAT ✨, 김기찬

#30 [SWEP-75] 메모 조회, 검색 API 연결
  app/src/main/java/com/umc/sweepic/data/datasource/MemoDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/MemoDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/BaseResponse.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/MoveImagesRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/MemoFolderDetailResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/RecordMemoListResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/MemoRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/MemoService.kt
  app/src/main/java/com/umc/sweepic/di/DataSourceModule.kt
  app/src/main/java/com/umc/sweepic/di/RepositoryModule.kt
  app/src/main/java/com/umc/sweepic/di/ServiceModule.kt
  app/src/main/java/com/umc/sweepic/domain/model/MemoFolderDetailModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/RecordMemoListModel.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/MemoRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/record/Adapter/MemoAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/Adapter/MemoDetailImageAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/Adapter/ViewPagerAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/FolderSelectDialog.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoDetailFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoFolder.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoFolderViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoFragment.kt
  app/src/main/res/layout/item_memo_folder.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values-v23/themes.xml
  app/src/main/res/values/themes.xml
Labels: FEAT ✨, 서영아

#35 [SWEP-90] 온보딩 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/sweepic/data/datasource/OnboardingDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/OnboardingDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/GoalCountRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/NameRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/NameResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/OnboardingRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/OnboardingService.kt
  app/src/main/java/com/umc/sweepic/di/DataSourceModule.kt
  app/src/main/java/com/umc/sweepic/di/RepositoryModule.kt
  app/src/main/java/com/umc/sweepic/di/ServiceModule.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/UpdateUserNameResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/OnboardingRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/OnboardingStep1Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/OnboardingStep3Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/OnboardingViewModel.kt
Labels: FEAT ✨, 서영아

#44 [SWEP-92] 사진 정리 화면 기능 구현
  app/src/main/java/com/umc/sweepic/data/datasource/sweep/SweepDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/GalleryDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/SweepDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/CreateMemoFolderRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/CreateTextFolderRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/DeleteImageRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/MoveTrashRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/TagRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/TrashImageRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/sweep/UpdateImageRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/AiTagResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/CreateMemoFolderResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/CreateTextFolderResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/DeleteImageResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/MoveTrashResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/TagInfoResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/TagResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/sweep/UpdateImageResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/SweepRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/SweepService.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/CreateMemoFolderRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/CreateTextFolderRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/DeleteImageRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/MoveTrashRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/TagRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/TrashImageRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/sweep/UpdateImageRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/AiTagResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/CreateMemoFolderResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/CreateTextFolderResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/DeleteImageResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/MoveTrashResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/TagInfoResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/TagResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/UpdateImageResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/sweep/GalleryModel.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/SweepRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/SweepActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/SweepViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/TrashActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/dialog/SweepTagDialog.kt
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/font/pretendard_regular.ttf
  app/src/main/res/layout/activity_move.xml
  app/src/main/res/layout/activity_sweep.xml
  app/src/main/res/layout/activity_trash.xml
  app/src/main/res/layout/dialog_add_existing_folder.xml
  app/src/main/res/layout/dialog_add_new_album.xml
  app/src/main/res/layout/dialog_bottom_sheet_album.xml
  app/src/main/res/layout/dialog_bottom_sheet_memo.xml
  app/src/main/res/layout/dialog_input_tag.xml
  app/src/main/res/layout/dialog_trash.xml
  app/src/main/res/layout/dialog_trash_deleted.xml
  app/src/main/res/layout/item_add_memo_folder.xml
  app/src/main/res/layout/item_existing_folder.xml
  app/src/main/res/values/appearances.xml
Labels: FEAT ✨, 김기찬

#46 [SWEP-102] 카카오 로그인 API 연결
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/sweepic/SweepicApplication.kt
  app/src/main/java/com/umc/sweepic/data/datasource/LoginDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/LoginDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/LoginResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/MemoFolderDetailResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/RecordMemoListResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/LoginRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/MemoRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/LoginService.kt
  app/src/main/java/com/umc/sweepic/di/DataSourceModule.kt
  app/src/main/java/com/umc/sweepic/di/NetworkModule.kt
  app/src/main/java/com/umc/sweepic/di/RepositoryModule.kt
  app/src/main/java/com/umc/sweepic/di/ServiceModule.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/LoginModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/MemoFolderDetailModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/sweep/RecordMemoListModel.kt
  app/src/main/java/com/umc/sweepic/domain/repository/LoginRepository.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/MemoRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/LoginActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/SplashActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/login/LoginActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/login/LoginViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/login/WebViewActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingStep1Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingStep2Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingStep3Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingStep4Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoFolder.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoFolderViewModel.kt
  app/src/main/java/com/umc/sweepic/util/network/AuthInterceptor.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_web_view.xml
  settings.gradle.kts
Labels: FEAT ✨, 서영아

#47 [SWEP-95] 히스토리 인기 태그 불러오기 기능 수정
  app/src/main/java/com/umc/sweepic/data/datasource/HistoryDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/HistoryDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/HistoryRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/HistoryService.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/HistoryRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/record/Adapter/HistoryBestPicAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/Adapter/HistoryTagAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/Adapter/MemoDetailImageAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryTagFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryTagViewModel.kt
  app/src/main/res/layout/fragment_history_tag.xml
Labels: FEAT ✨, 서영아

#50 [SWEP-97] 메모 수정 API 연결
  app/src/main/java/com/umc/sweepic/data/datasource/MemoDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/MemoDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/UpdateFolderNameRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/UpdateMemoTextRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/MemoRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/MemoService.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/MemoRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoDetailFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoFolderViewModel.kt
  app/src/main/res/layout/fragment_memo_detail.xml
Labels: FEAT ✨, 서영아

#52 [SWEP-108] 로그아웃 기능 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/umc/sweepic/data/datasource/MypageDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/MypageDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/MypageRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/MypageService.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/MypageRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/SplashActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/login/LoginViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/mypage/MyPageFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/mypage/MypageViewModel.kt
  app/src/main/java/com/umc/sweepic/util/network/AuthInterceptor.kt
Labels: FEAT ✨, 서영아

#54 [SWEP-109] 메모장, 온보딩 UI 수정
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingStep3Activity.kt
  app/src/main/java/com/umc/sweepic/presentation/record/RecordFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/FolderDeleteDialog.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoDetailFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/memo/PhotoDeleteDialog.kt
  app/src/main/res/drawable/bg_dialog.xml
  app/src/main/res/drawable/bg_popup_menu.xml
  app/src/main/res/layout/activity_onboarding_step3.xml
  app/src/main/res/layout/dialog_folder_delete.xml
  app/src/main/res/layout/dialog_photo_delete.xml
  app/src/main/res/layout/fragment_memo_detail.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/popup_memo_menu.xml
  app/src/main/res/layout/popup_selection_memo.xml
Labels: UI 🖌, 서영아

#55 [SWEP-109] 메모장 수정
  app/src/main/java/com/umc/sweepic/presentation/record/memo/MemoDetailFragment.kt
  app/src/main/res/layout/fragment_memo_detail.xml
Labels: REFACTOR 🔨, 서영아

#58 [SWEP-105] 챌린지 생성 기능 구현
  app/src/main/java/com/umc/sweepic/data/datasource/challenge/ChallengeDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/challenge/ChallengeDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/GalleryDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/challenge/GoalChallengeRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/challenge/LocationChallengeRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/challenge/LocationInfoRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/challenge/WeekChallengeRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/challenge/CommonChallengeResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/challenge/GetChallengeResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/challenge/GoalChallengeResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/challenge/LocationInfoResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/challenge/ChallengeRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/GalleryRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/ChallengeService.kt
  app/src/main/java/com/umc/sweepic/di/DataSourceModule.kt
  app/src/main/java/com/umc/sweepic/di/RepositoryModule.kt
  app/src/main/java/com/umc/sweepic/di/ServiceModule.kt
  app/src/main/java/com/umc/sweepic/domain/model/ChallengeWithImages.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/challenge/GoalChallengeRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/challenge/LocationChallengeRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/challenge/LocationInfoRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/challenge/WeekChallengeRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/challenge/CommonChallengeResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/challenge/GetChallengeResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/challenge/GoalChallengeResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/challenge/LocationInfoResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/sweep/GalleryModel.kt
  app/src/main/java/com/umc/sweepic/domain/repository/challenge/ChallengeRepository.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/GalleryRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/ChallengeAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/ChallengeFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/ChallengeListFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/ChallengeViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/InProgressChallengeFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/NewChallengeFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/SweepActivity.kt
  app/src/main/java/com/umc/sweepic/util/extension/ImageInfo.kt
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/fragment_challenge_list.xml
  app/src/main/res/layout/item_vp.xml
Labels: FEAT ✨, 김기찬

#56 [SWEP-103] 어워드 api
  app/src/main/java/com/umc/sweepic/data/datasource/AwardDataSource.kt
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/AwardDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/ImageIdCheckRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/request/ModifyAwardRequestDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/CreateAwardResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/GetAwardResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/ImageIdCheckResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/dto/response/ModifyAwardResponseDto.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/AwardRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/AwardService.kt
  app/src/main/java/com/umc/sweepic/di/DataSourceModule.kt
  app/src/main/java/com/umc/sweepic/di/RepositoryModule.kt
  app/src/main/java/com/umc/sweepic/di/ServiceModule.kt
  app/src/main/java/com/umc/sweepic/domain/model/LastBestPhotoItem.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/award/ImageIdCheckRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/request/award/ModifyAwardRequestModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/award/CreateAwardResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/award/GetAwardResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/award/ImageIdCheckResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/model/response/award/ModifyAwardResponseModel.kt
  app/src/main/java/com/umc/sweepic/domain/repository/sweep/AwardRepository.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/Award.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/BestPhotoAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/ChoicePhotoAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryLastBestAdapter.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryLastBestFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryLastBestViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryMonthChoiceFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryMonthChoiceViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryMonthFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/HistoryMonthViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/ItemHistoryLastBest.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/SelectedPhoto.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/award/SharedMonthPhotoViewModel.kt
  app/src/main/res/drawable/bg_selected_photo.xml
  app/src/main/res/drawable/ic_choice_delete.xml
  app/src/main/res/layout/fragment_history.xml
  app/src/main/res/layout/fragment_history_last_best.xml
  app/src/main/res/layout/fragment_history_month.xml
  app/src/main/res/layout/fragment_history_month_choice.xml
  app/src/main/res/layout/item_best_photo.xml
  app/src/main/res/layout/item_choice_photo.xml
  app/src/main/res/layout/item_history_last_best.xml
  app/src/main/res/navigation/main_graph.xml
Labels: FEAT ✨, 조성은

#62 모듈 수정
  app/src/main/java/com/umc/sweepic/di/DataSourceModule.kt
Labels: FIX 🐞

#66 [SWEP-115] 히스토리 기능 수정
  app/src/main/java/com/umc/sweepic/data/datasource/HistoryDataSource.kt
  app/src/main/java/com/umc/sweepic/data/repositoryImpl/sweep/HistoryRepositoryImpl.kt
  app/src/main/java/com/umc/sweepic/data/service/HistoryService.kt
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryTagViewModel.kt
Labels: FIX 🐞, REFACTOR 🔨, 서영아

#69 [SWEP-116] UI 수정
  app/src/main/java/com/umc/sweepic/presentation/login/LoginActivity.kt
  app/src/main/java/com/umc/sweepic/presentation/onboarding/OnboardingStep2Activity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_memo.xml
Labels: FIX 🐞, REFACTOR 🔨, 서영아

#71 [SWEP-117] 챌린지 생성 오류 수정
  app/src/main/java/com/umc/sweepic/data/datasourceImpl/sweep/GalleryDataSourceImpl.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/ChallengeFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/ChallengeViewModel.kt
  app/src/main/java/com/umc/sweepic/presentation/challenge/NewChallengeFragment.kt
  app/src/main/java/com/umc/sweepic/presentation/sweep/dialog/SweepTagDialog.kt
  app/src/main/java/com/umc/sweepic/util/extension/ImageInfo.kt
  app/src/main/res/layout/activity_challenge.xml
  app/src/main/res/layout/fragment_challenge.xml
  app/src/main/res/layout/item_vp.xml
Labels: FIX 🐞, 김기찬

#74 [SWEP-118] 태그 디자인 수정
  app/src/main/java/com/umc/sweepic/presentation/sweep/SweepActivity.kt
Labels: FIX 🐞, 김기찬

#76 [SWEP-119] 히스토리 UI 수정
  app/src/main/java/com/umc/sweepic/presentation/record/history/HistoryFragment.kt
  app/src/main/res/layout/fragment_history.xml
Labels: UI 🖌, 서영아
